# Generated by Django 4.0.4 on 2022-05-28 15:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0004_images_posted_on_images_updated_on'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='images',
            options={'ordering': ['-posted_on']},
        ),
    ]
